# Generated by Django 5.1 on 2024-09-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_series', models.IntegerField()),
                ('agrupamento_muscular', models.CharField(max_length=100)),
            ],
        ),
    ]
