# Generated by Django 5.1 on 2024-10-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gymsync', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('horario', models.TimeField()),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='app_gymsync.rotina')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gymsync.treino')),
            ],
            options={
                'unique_together': {('rotina', 'dia_semana', 'horario')},
            },
        ),
    ]
