# Generated by Django 5.1 on 2024-11-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gymsync', '0005_editartreino'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
