name: Build and deploy Python app to Azure Web App - gymsync

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v4

     
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

     
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

     
      - name: Clean up testing files (if they exist)
        run: |
          [ -f db.sqlite3 ] && rm db.sqlite3 || echo "db.sqlite3 not found, skipping"
          [ -f .env ] && rm .env || echo ".env not found, skipping"

    
      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r


      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  

    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app


      - name: Unzip artifact for deployment
        run: unzip release.zip


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          auth-type: 'SERVICE_PRINCIPAL' 


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'gymsync'
          slot-name: 'Production'
